language: node_js
notifications:
  email: false
node_js:
  - '5'
cache:
  directories:
    - node_modules
after_success:
  - npm run deploy:coverage
  - npm run deploy:gh-pages
deploy:
  provider: npm
  email: aniquilatorbloody@gmail.com
  'on':
    branch: master
    tags: true
